from pathlib import Path
from html import escape

ROOT=Path(__file__).resolve().parents[1]
imgs={
 'hero-concert':('Black-and-white band performing under stage lights.','Tim Toomey / Unsplash'),
 'concert-02':('Audience with raised hands facing a brightly lit stage.','Tomas Malik / Unsplash'),
 'concert-03':('Vocalist leaning into a concert crowd.','Evgeniy Smersh / Unsplash'),
 'event-01':('Crowd gathered indoors for an evening celebration.','Filip Rankovic Grobgaard / Unsplash'),
 'event-02':('People moving through a large indoor event.','Jakob Dalbjorn / Unsplash'),
 'event-03':('Colorful floral table setting prepared for a gathering.','CHUTTERSNAP / Unsplash'),
 'event-04':('Guest holding a glass during a reception.','Virginia Marinova / Unsplash'),
 'graduation-01':('Graduate smiling outdoors in a black cap and gown.','Kari Bjorn Photography / Unsplash'),
 'graduation-02':('Graduate blowing gold confetti toward the camera.','Sebastian Latorre / Unsplash'),
 'graduation-03':('Graduate in a navy suit and academic gown.','Patrick Otim / Unsplash'),
 'travel-01':('Turquoise ocean breaking against a rocky shoreline.','Drew Dau / Unsplash'),
 'travel-02':('Coastal road between green cliffs and blue ocean.','Peter Thomas / Unsplash'),
 'travel-03':('Quiet road winding through dark hills toward the sea.','Irvin Aloise / Unsplash'),
}
sections=[
 {'slug':'graduation','n':'01','title':'Graduation Photos','short':'Graduation','eyebrow':'Portraits / milestones','intro':'Graduation days move fast. I like to slow them down—some posed, some candid, all made to feel like you.','note':'Solo sessions, friends, families, campus walks, and the small in-between moments that make the day yours.','approach':'We’ll make the photos you know you need, then leave enough room for the ones you didn’t plan.','cta':'Planning a graduation session? Tell me your school, date, and the kind of photos you want to leave with.','cover':'graduation-02','support':'graduation-03','images':['graduation-02','graduation-03','graduation-01']},
 {'slug':'events','n':'02','title':'Events','short':'Events','eyebrow':'Gatherings / celebrations','intro':'I’m there for the big moments and the smaller ones around them—the room, the details, and the people who make it feel alive.','note':'Coverage can stay documentary, lean polished, or land somewhere in between depending on the day.','approach':'I pay attention to the schedule without treating it like the only thing worth photographing.','cta':'Send the date, location, rough schedule, and what matters most to you. That’s enough to start.','cover':'event-01','support':'event-04','images':['event-01','event-04','event-03','event-02']},
 {'slug':'concerts','n':'03','title':'Concerts','short':'Concerts','eyebrow':'Live music / low light','intro':'Loud rooms, difficult light, and the half-second when everything lines up.','note':'I’m interested in the full room—not only the person on stage, but the crowd, the light, and what happens at the edges.','approach':'This is a growing part of my work. I’d rather show a small set I believe in than pretend the archive is bigger than it is.','cta':'For live coverage, send the artist, venue, date, access details, and where the photographs need to end up.','cover':'concert-03','support':'hero-concert','images':['concert-03','hero-concert','concert-02']},
 {'slug':'travel','n':'04','title':'Personal / Travel','short':'Travel','eyebrow':'Places / no shot list','intro':'Photos I make when there isn’t a client, a timeline, or a shot list—just a place I want to remember clearly.','note':'This is the quieter side of the portfolio and the place where new visual ideas usually begin.','approach':'I keep this work here because it changes how I notice light, distance, and small details everywhere else.','cta':'Have a travel, editorial, or personal project that feels connected to this work? Send it my way.','cover':'travel-03','support':'travel-01','images':['travel-03','travel-01','travel-02']},
]
by_slug={x['slug']:x for x in sections}

def picture(name,cls='',eager=False,alt=None):
    alt=imgs[name][0] if alt is None else alt
    load='eager' if eager else 'lazy'
    priority=' fetchpriority="high"' if eager else ''
    return f'<picture class="{cls}"><source srcset="assets/images/{name}.webp" type="image/webp"><img src="assets/images/{name}.jpg" alt="{escape(alt)}" loading="{load}" decoding="async"{priority}></picture>'

def ambient():return '<div class="ambient" aria-hidden="true"><div class="particles"></div></div>'

def header(page):
    active=lambda n:' class="active"' if page==n or (n=='work' and page in by_slug) else ''
    return f'''<a class="skip" href="#main">Skip to content</a><header class="site-header"><div class="header-inner"><a class="brand" href="index.html"><span class="brand-mark" data-short>FS</span><span><strong data-name>Frankie Schulte</strong><small data-role>Photographer</small></span></a><nav class="primary-nav" aria-label="Primary"><a href="work.html"{active('work')}>Work</a><a href="about.html"{active('about')}>About</a><a href="inquire.html"{active('inquire')}>Inquire</a></nav><div class="header-actions"><button class="palette-btn" data-theme-open type="button"><span class="palette-dot"></span><span class="palette-label">Palette</span></button><button class="icon-btn menu-btn" id="menu-btn" type="button" aria-label="Open menu" aria-expanded="false"><span class="menu-lines"></span></button></div></div></header><div class="mobile-menu" id="mobile-menu" aria-hidden="true"><div class="mobile-inner"><p class="eyebrow">Portfolio / select a section</p><nav class="mobile-nav"><a href="graduation.html">Graduation Photos <span>01</span></a><a href="events.html">Events <span>02</span></a><a href="concerts.html">Concerts <span>03</span></a><a href="travel.html">Personal / Travel <span>04</span></a><a href="about.html">About <span>→</span></a><a href="inquire.html">Inquire <span>→</span></a></nav><div class="mobile-meta"><span data-location>Your city / region</span><a data-email-link data-email>your-email@example.com</a></div></div></div>'''

def palette():return '''<div class="theme-scrim" id="theme-scrim"></div><aside class="theme-panel" id="theme-panel" aria-hidden="true"><div class="theme-head"><h2>Choose a palette</h2><button class="icon-btn" id="theme-close">Close</button></div><p class="theme-intro">The photographs stay in charge. This changes the grainy light behind them, gradient type, and small accents.</p><div class="theme-options"><button class="theme-preset" data-preset="orange-violet"><span class="swatch" style="--sa:#ff6a2a;--sb:#7653ff"></span><span><strong>Orange + violet</strong><small>Warm, electric, nocturnal.</small></span><span>01</span></button><button class="theme-preset" data-preset="monochrome"><span class="swatch" style="--sa:#f4f1ea;--sb:#585861"></span><span><strong>Monochrome</strong><small>Silver, charcoal, nearly neutral.</small></span><span>02</span></button><button class="theme-preset" data-preset="ember-plum"><span class="swatch" style="--sa:#ff7a24;--sb:#6c164f"></span><span><strong>Ember + plum</strong><small>Darker, warmer, less blue.</small></span><span>03</span></button><button class="theme-preset" data-preset="cobalt-amber"><span class="swatch" style="--sa:#ffb000;--sb:#315cff"></span><span><strong>Cobalt + amber</strong><small>Cool shadows, warm highlight.</small></span><span>04</span></button></div><div class="custom-theme"><h3>Or pick any two colors</h3><div class="colors"><label>Color one<input id="color-a" type="color" value="#ff6a2a"></label><label>Color two<input id="color-b" type="color" value="#7653ff"></label></div><p class="theme-note">Saved in this browser. Change the public default in <code>assets/js/site-config.js</code>.</p></div></aside>'''

def footer():return '''<footer class="site-footer"><div class="footer-inner shell"><div><a class="footer-name" href="index.html" data-name>Frankie Schulte</a><p class="footer-copy">Graduation portraits, events, concerts, and personal travel photographs.</p></div><div class="footer-meta"><a class="text-link" href="inquire.html">Start a conversation ↗</a><p>© <span data-year></span> <span data-name>Frankie Schulte</span></p><p data-demo>Preview uses credited demo photography and placeholder contact details.</p></div></div></footer>'''

def page(title,desc,name,main):return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)}</title><meta name="description" content="{escape(desc)}"><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="assets/css/styles.css"><script src="assets/js/site-config.js"></script></head><body>{header(name)}{palette()}<main id="main">{main}</main>{footer()}<script src="assets/js/app.js"></script></body></html>'''

def home():
    rows=''.join(f'<a class="contents-item" href="{s["slug"]}.html"><span class="contents-number">{s["n"]}</span><span class="contents-title">{escape(s["title"])}</span><span class="contents-copy">{escape(s["note"])}</span><span class="contents-preview">{picture(s["cover"],alt="")}</span></a>' for s in sections)
    feats=[]
    for i,s in enumerate(sections):
        rev=' reverse' if i%2 else ''
        feats.append(f'<section class="feature{rev}"><div class="feature-grid editorial"><div class="feature-copy"><div class="feature-label"><p class="eyebrow">Practice {s["n"]}</p><span class="eyebrow">{escape(s["eyebrow"])}</span></div><h2 class="display feature-title">{escape(s["short"])}</h2><p>{escape(s["intro"])}</p><a class="text-link" href="{s["slug"]}.html">See the photographs ↗</a></div><div class="feature-images"><div class="feature-main">{picture(s["cover"])}<span class="image-note">Demo image / replace before launch</span></div><div class="feature-support">{picture(s["support"])}</div></div></div></section>')
    main=f'''<section class="hero"><div class="hero-media">{ambient()}{picture('hero-concert','hero-picture',True)}<div class="wash"></div><div class="vignette"></div></div><div class="hero-copy editorial"><div class="hero-main"><p class="eyebrow">Photographer · <span data-location>Your city / region</span></p><h1 class="display hero-title">Hi, I’m <span class="gradient-text">Frankie</span><br>Schulte.</h1><div class="hero-grid"><p class="hero-lead">I photograph graduations, events, live music, and the places I end up along the way.</p><p class="hero-aside">People first. A little direction when it helps. Room for the real moment when it happens.</p></div><div class="hero-actions"><a class="button" href="graduation.html">See graduation work</a><a class="button outline" href="inquire.html">Ask about a shoot</a></div></div><div class="hero-folio"><p class="eyebrow">Selected work / preview edition</p><a href="#contents">Scroll ↓</a></div></div></section><section class="contents" id="contents"><div class="editorial"><div class="contents-head"><h2 class="display">Start here.</h2><p>Graduation comes first right now. Events, concerts, and personal work follow without making the whole portfolio about one kind of job.</p></div><div class="contents-list">{rows}</div></div></section>{''.join(feats)}<section class="quote"><div class="quote-grid editorial"><p class="eyebrow">A little about me</p><div class="quote-copy"><blockquote>“Most people tell me they feel awkward in front of a camera. That’s completely normal.”</blockquote><p>I don’t need you to show up knowing what to do. We can walk around, talk, try a few things, and make photographs that still feel like you.</p><a class="text-link" href="about.html">More about how I work ↗</a></div></div></section><section class="cta">{ambient()}<div class="cta-content editorial"><p class="eyebrow">Have something in mind?</p><h2 class="display">Tell me what the day looks like.</h2><p>A date, a location, and a rough idea are enough for the first message. We can figure out the rest together.</p><a class="button" href="inquire.html">Start a conversation</a></div></section>'''
    return page('Frankie Schulte — Photography','Graduations, events, concerts, and personal travel photography by Frankie Schulte.','home',main)

def work():
    cards=''.join(f'<a class="work-card" href="{s["slug"]}.html">{picture(s["cover"])}<div class="work-copy"><p class="eyebrow">{s["n"]} / {escape(s["eyebrow"])}</p><h2>{escape(s["title"])}</h2><p>{escape(s["intro"])}</p></div></a>' for s in sections)
    main=f'<section class="page-hero">{ambient()}<div class="vignette"></div><div class="page-hero-inner editorial"><p class="eyebrow">Portfolio / four sections</p><h1 class="display">The work I want to keep making.</h1><p class="page-lead">Graduation comes first right now, followed by events, concerts, and the photographs I make while traveling. As the work changes, this page can change with it.</p></div></section><section class="work-section"><div class="editorial"><div class="work-grid">{cards}</div></div></section>'
    return page('Work — Frankie Schulte','Graduation, event, concert, and personal travel photography.','work',main)

def gallery(slug):
    s=by_slug[slug];items=[]
    for i,n in enumerate(s['images'],1):
        alt,credit=imgs[n];caption=f'{i:02d} / Demo image · {credit}'
        items.append(f'<figure class="gallery-item"><button class="gallery-button" data-lightbox="assets/images/{n}.jpg" data-alt="{escape(alt)}" data-caption="{escape(caption)}"><span class="gallery-frame">{picture(n)}</span></button><figcaption class="caption"><span>{i:02d} / demo photograph</span><span>{escape(credit)}</span></figcaption></figure>')
    main=f'<section class="gallery-hero"><a class="back" href="work.html">← All work</a><div class="hero-media">{ambient()}{picture(s["cover"],"hero-picture",True)}<div class="wash"></div><div class="vignette"></div></div><div class="hero-copy editorial"><div class="hero-main"><p class="eyebrow">{s["n"]} / {escape(s["eyebrow"])}</p><h1 class="display hero-title">{escape(s["title"])}</h1><p class="hero-lead">{escape(s["intro"])}</p></div></div></section><section class="gallery-intro"><div class="gallery-intro-grid editorial"><p class="eyebrow">How I think about it</p><p class="gallery-quote">{escape(s["note"])}</p><p class="gallery-note">{escape(s["approach"])}</p></div></section><section class="gallery-section"><div class="editorial"><div class="gallery-toolbar"><div><p class="eyebrow">Selected photographs</p><h2>A small edit.</h2></div><div class="view-toggle" data-gallery-toggle="#gallery"><button data-view="sequence" aria-pressed="true">Sequence</button><button data-view="contact" aria-pressed="false">Contact sheet</button></div></div><div class="gallery-grid" id="gallery">{"".join(items)}</div></div></section><section class="cta">{ambient()}<div class="cta-content editorial"><p class="eyebrow">Let’s make something</p><h2 class="display">{escape(s["cta"])}</h2><p>Based in <span data-location>Your city / region</span>. <span data-travel>Available to travel when the project makes sense.</span></p><a class="button" href="inquire.html?type={slug}">Ask about this</a></div></section>'
    return page(f'{s["title"]} — Frankie Schulte',s['intro'],slug,main)

def about():
    main=f'<section class="page-hero">{ambient()}<div class="vignette"></div><div class="page-hero-inner editorial"><p class="eyebrow">About / a real person, not a brand paragraph</p><h1 class="display">Hi, I’m Frankie.</h1><p class="page-lead">I like photographs that feel relaxed, honest, and a little lived-in.</p></div></section><section class="about-section"><div class="about-grid editorial"><div class="portrait-slot">{ambient()}<div class="portrait-content"><span class="monogram">FS</span><p class="placeholder-note">Portrait slot / replace this graphic with an actual photograph of Frankie before launch.</p></div></div><div class="about-copy"><h2>I’m usually looking for the moment around the obvious one.</h2><p>The laugh after the posed photo. The room settling before a speech. The second a stage light catches someone just right.</p><p>My work moves between graduations, gatherings, live shows, and personal trips. The subjects change, but I’m usually looking for the same thing—people and places that still feel like themselves in the frame.</p><p>I want the process to feel straightforward. I’ll offer direction when it’s useful, stay out of the way when it isn’t, and make sure we know what matters before the day begins.</p><div class="details"><div><h3>Currently photographing</h3><ul><li>Graduation sessions</li><li>Events and celebrations</li><li>Concerts and live music</li><li>Personal / editorial projects</li></ul></div><div><h3>Based in</h3><ul><li data-location>Your city / region</li><li data-travel>Available to travel.</li><li><a data-email-link data-email>your-email@example.com</a></li></ul></div></div><p class="demo-note" data-demo>This copy is intentionally personal but still a starting point. Replace any sentence that doesn’t sound like Frankie.</p></div></div></section>'
    return page('About — Frankie Schulte','About Frankie Schulte and the approach behind the photography.','about',main)

def inquire():
    main=f'<section class="page-hero">{ambient()}<div class="vignette"></div><div class="page-hero-inner editorial"><p class="eyebrow">Inquire / no hard sell</p><h1 class="display">Tell me what you’re planning.</h1><p class="page-lead">A date, a location, and a rough idea are plenty for the first message. It doesn’t need to be polished.</p></div></section><section class="inquire-section"><div class="inquire-grid editorial"><aside class="contact-aside"><div class="contact-sticky"><p class="eyebrow">Direct contact</p><a class="contact-link" data-email-link><span data-email>your-email@example.com</span><span>↗</span></a><a class="contact-link" data-instagram-link target="_blank"><span data-instagram>@your-handle</span><span>↗</span></a><div class="contact-meta"><p data-location>Your city / region</p><p data-travel>Available to travel.</p></div><p class="demo-note" data-demo>Replace these placeholder details in <code>assets/js/site-config.js</code>.</p></div></aside><form class="inquiry-form" id="inquiry-form"><div class="form-grid"><label class="field"><span class="label">Your name *</span><input class="control" name="name" required></label><label class="field"><span class="label">Email *</span><input class="control" name="email" type="email" required></label></div><div class="form-grid"><label class="field"><span class="label">What are we photographing? *</span><select class="control" name="projectType" required><option value="">Choose one</option><option value="graduation">Graduation photos</option><option value="events">Event</option><option value="concerts">Concert / live music</option><option value="travel">Personal / editorial</option><option value="other">Something else</option></select></label><label class="field"><span class="label">Date or timeline</span><input class="control" name="timeline" placeholder="May 18, or sometime this fall"></label></div><label class="field"><span class="label">City, venue, school, or location</span><input class="control" name="location"></label><div class="form-grid"><label class="field"><span class="label">What do you need the photos for?</span><input class="control" name="usage" placeholder="Personal, social, press, website…"></label><label class="field"><span class="label">Budget, if you have one</span><input class="control" name="budget" placeholder="Optional"></label></div><label class="field"><span class="label">Tell me about it *</span><textarea class="control" name="details" required></textarea></label><div class="form-actions"><button class="button">Prepare email</button><p class="form-help">This creates a draft in your own email app. It never pretends a message was sent when it wasn’t.</p></div><p class="status" id="status"></p></form></div></section>'
    return page('Inquire — Frankie Schulte','Contact Frankie Schulte about a photography project.','inquire',main)

pages={'index.html':home(),'work.html':work(),'about.html':about(),'inquire.html':inquire()}
for s in sections:pages[s['slug']+'.html']=gallery(s['slug'])
for name,html in pages.items():(ROOT/name).write_text(html,encoding='utf-8')
print('generated',len(pages),'pages')
